Groep4 devbranch
DevOps-2023-Casusmaatjes/Jaar2Blok4Casus pull request #16
Opened 2023-06-13 09:14 UTC by thmaz

Map Game1Page kan toegevoegd worden aan main
Profile.html, profile.css en script.js in ProfilePage zijn aangepast.

2023-06-13 09:19 UTC, Roelkuhh043 approved these changes

2023-06-13 13:31 UTC, ProgrammerGhostPrK requested changes
Het level van het profiel even zo laten staan en "punten" weghalen, er komen meerdere games op de site en dus is het niet logisch om de punten van 1 spel bij te houden op het profiel.

2023-06-14 09:47 UTC, Ozziehman commented
Dezer merge verwijderd veel van de main branch, aub fixen

2023-06-14 14:33 UTC, RainbowNova approved these changes
👍

2023-06-21 10:32 UTC, closed without merging